config/routes.rb
Rails.application.routes.draw do
  resources :splits
  resources :items
  resources :bosses
  resources :teams
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boss.rb
class Boss < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :boss
  has_many :splits
end

app/models/split.rb
class Split < ApplicationRecord
  belongs_to :item
  belongs_to :team



end

app/models/team.rb
class Team < ApplicationRecord
  has_many :splits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bosses_controller.rb
class BossesController < ApplicationController
  before_action :set_boss, only: [:show, :edit, :update, :destroy]

  # GET /bosses
  # GET /bosses.json
  def index
    @bosses = Boss.all
  end

  # GET /bosses/1
  # GET /bosses/1.json
  def show
  end

  # GET /bosses/new
  def new
    @boss = Boss.new
  end

  # GET /bosses/1/edit
  def edit
  end

  # POST /bosses
  # POST /bosses.json
  def create
    @boss = Boss.new(boss_params)

    respond_to do |format|
      if @boss.save
        format.html { redirect_to @boss, notice: 'Boss was successfully created.' }
        format.json { render :show, status: :created, location: @boss }
      else
        format.html { render :new }
        format.json { render json: @boss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bosses/1
  # PATCH/PUT /bosses/1.json
  def update
    respond_to do |format|
      if @boss.update(boss_params)
        format.html { redirect_to @boss, notice: 'Boss was successfully updated.' }
        format.json { render :show, status: :ok, location: @boss }
      else
        format.html { render :edit }
        format.json { render json: @boss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bosses/1
  # DELETE /bosses/1.json
  def destroy
    @boss.destroy
    respond_to do |format|
      format.html { redirect_to bosses_url, notice: 'Boss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boss
      @boss = Boss.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def boss_params
      params.require(:boss).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :price, :boss_id)
    end
end

app/controllers/splits_controller.rb
class SplitsController < ApplicationController
  before_action :set_split, only: [:show, :edit, :update, :destroy]

  # GET /splits
  # GET /splits.json
  def index
    @splits = Split.all
    @splitSum = Split.sum(:splitAmt)
    @splitLast = Split.last.item.name
  end

  # GET /splits/1
  # GET /splits/1.json
  def show
  end

  # GET /splits/new
  def new
    @split = Split.new
  end

  # GET /splits/1/edit
  def edit
  end

  # POST /splits
  # POST /splits.json
  def create
    @split = Split.new(split_params)

    respond_to do |format|
      if @split.save
        format.html { redirect_to @split, notice: 'S
plit was successfully created.' }
        format.json { render :show, status: :created, location: @split }
      else
        format.html { render :new }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /splits/1
  # PATCH/PUT /splits/1.json
  def update
    respond_to do |format|
      if @split.update(split_params)
        format.html { redirect_to @split, notice: 'Split was successfully updated.' }
        format.json { render :show, status: :ok, location: @split }
      else
        format.html { render :edit }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /splits/1
  # DELETE /splits/1.json
  def destroy
    @split.destroy
    respond_to do |format|
      format.html { redirect_to splits_url, notice: 'Split was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_split
      @split = Split.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def split_params
      params.require(:split).permit(:item_id, :soldFor, :splitAmt, :team_id, :inName, :killCount)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bosses_helper.rb
module BossesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/splits_helper.rb
module SplitsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/bosses/_form.html.erb
<%= form_with(model: boss, local: true) do |form| %>
  <% if boss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boss.errors.count, "error") %> prohibited this boss from being saved:</h2>

      <ul>
        <% boss.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bosses/edit.html.erb
<h1>Editing Boss</h1>

<%= render 'form', boss: @boss %>

<%= link_to 'Show', @boss %> |
<%= link_to 'Back', bosses_path %>

app/views/bosses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bosses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bosses.each do |boss| %>
      <tr>
        <td><%= boss.name %></td>
        <td><%= link_to 'Show', boss %></td>
        <td><%= link_to 'Edit', edit_boss_path(boss) %></td>
        <td><%= link_to 'Destroy', boss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boss', new_boss_path %>

app/views/bosses/new.html.erb
<h1>New Boss</h1>

<%= render 'form', boss: @boss %>

<%= link_to 'Back', bosses_path %>

app/views/bosses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @boss.name %>
</p>

<%= link_to 'Edit', edit_boss_path(@boss) %> |
<%= link_to 'Back', bosses_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :boss_id %>
    <%= collection_select(:item, :boss_id, Boss.all, :id, :name ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Boss</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.boss.name %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Boss:</strong>
  <%= @item.boss.name %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splits</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <ul>
      <li><%= link_to "Bosses", bosses_path %></li>
      <li><%= link_to "Items", items_path %></li>
      <li><%= link_to "Team Sizes", teams_path %></li>
      <li><%= link_to "Splits", splits_path %></li>
    </ul>
  </head>

  <body>
    <br><br>

    <%= yield %>
  </body>
</html>

app/views/splits/_form.html.erb
<%= form_with(model: split, local: true) do |form| %>
  <% if split.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(split.errors.count, "error") %> prohibited this split from being saved:</h2>

      <ul>
        <% split.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_id %>
    <%= collection_select(:split, :item_id, Item.all, :id, :name)%>
  </div>

  <div class="field">
    <%= form.label :soldFor %>
    <%= form.number_field :soldFor %>
  </div>

  <div class="field">
    <%= form.label :splitAmt %>
    <%= form.number_field :splitAmt %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= collection_select(:split, :team_id, Team.all, :id, :size   ) %>
  </div>

  <div class="field">
    <%= form.label :inName %>
    <%= form.text_field :inName %>
  </div>
  <div class="field">
    <%= form.label :kc %>
    <%= form.text_field :killCount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/splits/edit.html.erb
<h1>Editing Split</h1>

<%= render 'form', split: @split %>

<%= link_to 'Show', @split %> |
<%= link_to 'Back', splits_path %>

app/views/splits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Splits</h1>

<table>
  <thead>
    <tr>
      <th> Item Name </th>
      <th> Sold For </th>
      <th> Split Amount </th>
      <th> Team Size </th>
      <th> InName Purple </th>
      <th> Kill Count </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @splits.each do |split| %>
      <tr>
        <td><%= split.item.name %></td>
        <td><%= split.soldFor %></td>
        <td><%= split.splitAmt %></td>
        <td><%= split.team.size %></td>
        <td><%= split.inName %></td>
        <td><%= split.killCount %></td>
        <td><%= link_to 'Show', split %></td>
        <td><%= link_to 'Edit', edit_split_path(split) %></td>
        <td><%= link_to 'Destroy', split, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Split', new_split_path %>

<hr>
<h1>Summary</h1>
Sum of the Splits : <%= @splitSum %>
<br>
Latest Split Item : <%= @splitLast%>
Latest Split Amt : <%= %>

app/views/splits/new.html.erb
<h1>New Split</h1>

<%= render 'form', split: @split %>

<%= link_to 'Back', splits_path %>

app/views/splits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @split.item_id %>
</p>

<p>
  <strong>Soldfor:</strong>
  <%= @split.soldFor %>
</p>

<p>
  <strong>Splitamt:</strong>
  <%= @split.splitAmt %>
</p>

<p>
  <strong>Team:</strong>
  <%= @split.team_id %>
</p>

<p>
  <strong> Name Who Recieved Unique :</strong>
  <%= @split.inName %>
</p>

<p>
  <strong> KC :</strong>
  <%= @split.killCount %>
</p>

<%= link_to 'Edit', edit_split_path(@split) %> |
<%= link_to 'Back', splits_path %>